version: "3"

services:
  db:
    image: postgres:14.0
    container_name: postgres-server
    environment:
      POSTGRES_DB: dbforapi
      POSTGRES_USER: userforapi
      POSTGRES_PASSWORD: pwforapi
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "apidbuser", "-d", "apidb"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    platform: linux/amd64
    image: datawhales/fastapi-crud:0.1.0
    container_name: fastapi-server
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://userforapi:pwforapi@db:5432/dbforapi
    ports:
      - 7777:7777
    depends_on:
      db:
        condition: service_healthy
